### ISSUE TITLE
Various small cleanups

### ISSUE THREAD

**Issue by bs2609** [Phiggle/bizhawk-shuffler-2#29]
A collection of things that aren't really large enough to have their own issues:

- `SMAS_swap` looks to be replaceable with `twoplayers_withlives_swap` if `getsmb2mode` is merged into `gettogglecheck` behind a check for SMB2-U like so:
  ```lua
  elseif memory.read_u8(0x01FF00, "WRAM") == 6 then
  	return memory.read_u8(0x0004C4, "WRAM")
  ```

- `Rocket_Knight_Adventures_swap` should be replaceable with `singleplayer_withlives_swap` like so:
  ```lua
  p1gethp = function() return math.max(memory.read_s16_be(0xC040, "68K RAM"), -1) end,
  minhp = -1,
  ```
  Also, `memory.read_s16_be(0xB02C, "68K RAM")` is checked for 3 for special handling of a game over, but `gmode` specifically filters out a value of 3 at that address - it looks like the `gmode` check should be an `or (value) == 3` check instead of the `and (value) ~= 3` it is at present.

- `saturn_fix_string_endianness` can be removed as it isn't used or needed, Saturn games are already known to require BizHawk 2.10 to work properly anyway. There's also some similar commented out code in `Pebble_Beach_Golf_Links_swap` for this purpose that should be deleted as well.

- Kabuki Quantum Fighter has a `swap_exceptions` block for health being drained at the end of a level, however `singleplayer_withlives_swap` already has code to handle this exact situation - the `swap_exceptions` should probably be replaced with a `delay` value that covers the time between health deductions.

- Some metadata functions are not declaring variables as `local`:   e.g. SotN, Super GnG, Sonic 3D, Sonic Spinball, I.Q., Bubsy 3D were the ones I could find, but there may be more - this overwites any other value with those names in the general shuffler environment, will persist through other games being loaded, and doesn't seem to be used for any deliberate purpose, so they should be converted to `local` variables instead.

**Comment by Shadow-Hog** [comment]
No arguments against bullet 3, I've been meaning to nuke that dead code anyway. Nor arguments against bullet 5, I'm just gonna chalk that up to Lua naïveté on my part.

Bullet 2, that _may_ be true but I think I'd want to take a closer look before jumping at it, because I recall _RKA_ giving me a **whole** lot of shit trying to put it together.

**Comment by Phiggle** [comment]
Happy to make that comment on KQF, as I follow what you're saying now. And, I can help make that happen on bullets 3 and 5 then.

I remember RKA being a pain too. Appreciated if you do look into bullet 2, Shadow Hog.

Adding hashes for newer games as you describe should also be fine.

I do plan to get to these even if other bugs are jumping to the front of the line...

Thanks!

**Comment by Phiggle** [comment]
Updated with some resolutions and will be working through the rest.

**Comment by Phiggle** [comment]
Two additional updates made. I apologize, I now also realize I had not edited your comment before this set of changes and that you were the one updating resolutions. I will go back to leaving the comment alone for you to update or comment back - thank you.

**Comment by Phiggle** [comment]
I believe all the listed minor issues through today have been addressed. Thanks for finding these and for the detailed rundowns! I'd recommend opening a new issue for any similar findings, as a new batch of games' pull requests will go through fairly soon. I'll leave this open for now in case there is an error or omission.

**Comment by bs2609** [comment]
I think that that covers most things, the only minor outstanding points seem to be Crash 4 still being tagged as an NES title instead of GBA and the hash for the Japanese version of High Seas Havoc needs checking and possibly changing.

**Comment by bs2609** [comment]
Leaving a comment here so it's not forgotten (it can be moved to a new issue later if needed) - Jurassic Park was apparently not fixed earlier and needs updating. It's buried in the Discord discussion, so you'll either need to dredge up a complete solution or get the submitter to make a PR if they have it.

**Comment by Phiggle** [comment]
Thanks again for the review. 

I've checked the JP High Seas Havoc (Captain Lang) hash. It's not clear to me why, but replacing what's there with the SHA-1 hash simply doesn't work - the plugin does not recognize it. This might be solvable, but I am not sure what the problem is.

I see the discussion of Jurassic Park and can address that one too.

**Comment by bs2609** [comment]
> I've checked the JP High Seas Havoc (Captain Lang) hash. It's not clear to me why, but replacing what's there with the SHA-1 hash simply doesn't work - the plugin does not recognize it.

As long as the hash is checked to work, this isn't a problem - it's just odd that it's in a different format from the other hashes for the console.

Also to be fully clear, the bootleg Crash 4 is a **GBA** title and *not* an NES title - the gamelist entry was updated earlier to be correct, but every other mention was left stating NES as the console, which seems to have caused confusion. Things should be updated to say "GBA" everywhere.

**Comment by Phiggle** [comment]
Whoops! And I also misspoke about which Captain Lang hash was the working one. Let's fix those GBA references... thanks for the correction.
